# MakeFile
CC = gcc
ASM = nasm
CFLAGS = -ffreestanding -O2 -Wall -Wextra -nostdlib -nostartfiles
LDFLAGS =
SRC = src
BUILD = build

all: $(BUILD)/kernel.elf

$(BUILD):
	mkdir -p $(BUILD)

$(BUILD)/kernel.o: $(SRC)/kernel.c | $(BUILD)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD)/entry.o: $(SRC)/entry.S | $(BUILD)
	$(ASM) -f elf64 $< -o $@

$(BUILD)/kernel.elf: $(BUILD)/entry.o $(BUILD)/kernel.o
	$(CC) --ffreestanding -O2 -nostdlib -nostartfiles -Ttext 0x100000 \
		$^ -o $@

run: all
	qemu-system-x86_64 -kernel $(BUILD)/kernel.elf -serial stdio -display none

clean:
	rm -rf $(BUILD)